// Generated by CoffeeScript 1.6.3
(function() {
  var DbFacade, NOT_IMPLEMENTED, db, util;

  util = require('./util');

  NOT_IMPLEMENTED = util.NOT_IMPLEMENTED;

  db = require('./db');

  DbFacade = {
    getProjects: db.getProjects,
    getProject: db.getProject,
    getItems: db.getItems,
    getItem: db.getItem,
    getProjectItems: function(projectKey, type) {
      var query;
      query = {
        project: projectKey
      };
      if (type) {
        query.type = type;
      }
      return this.getItems(query);
    }
  };

  module.exports = DbFacade;

}).call(this);
